teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.3
    scale_linear_turbo:
      x: 0.08

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 1.2
    scale_angular_turbo:
      yaw: 0.4

    # See: https://forum.unity.com/attachments/ps4-jpg.74924/
    enable_button: 5
    enable_turbo_button: 7
