export WEBOTS_HOME=/usr/local/webots
export USERNAME=default
export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

alias cb='colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Debug'

test -f /opt/ros/humble/local_setup.bash && \
    source /opt/ros/humble/local_setup.bash
test -f /memristor/ros2_ws/install/local_setup.bash && \
    source /memristor/ros2_ws/install/local_setup.bash
test -f /memristor/.host/.Xauthority && \
    cp -p /memristor/.host/.Xauthority /memristor/.Xauthority
