controller_manager:
  ros__parameters:
    update_rate: 50

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffdrive_controller:
  ros__parameters:
    left_wheel_names: ["left_motor"]
    right_wheel_names: ["right_motor"]

    wheel_separation: 0.255583
    wheel_radius: 0.03157
    right_wheel_radius_multiplier: 1.0006331117442229

    linear.x.has_velocity_limits: true
    linear.x.min_velocity: -0.9
    linear.x.max_velocity: 0.9
    linear.x.has_acceleration_limits: true
    linear.x.min_acceleration: -0.9
    linear.x.max_acceleration: 0.9

    angular.z.has_velocity_limits: true
    angular.z.min_velocity: -3.0
    angular.z.max_velocity: 3.0
    angular.z.has_acceleration_limits: true
    angular.z.min_acceleration: -4.0
    angular.z.max_acceleration: 4.0


    publish_rate: 50.0
    use_stamped_vel: false
