controller_manager:
  ros__parameters:
    update_rate: 50

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffdrive_controller:
  ros__parameters:
    left_wheel_names: ["left_motor"]
    right_wheel_names: ["right_motor"]

    wheel_separation: 0.35
    wheel_radius: 0.073

    publish_rate: 50.0
    use_stamped_vel: true

joint_state_broadcaster:
  ros__parameters:
    extra_joints:
      - removal_motor   # Removal tool joint without encoder
      - CASTER          # Non-actuated caster joint #1
      - hingejoint      # Non-actuated caster joint #2
