float64 position            # rad
float64 max_velocity        # rad/s
float64 max_acceleration    # rad/s^2
float64 tolerance           # rad
float64 timeout             # s
string name                 # joint name
---
int8 result        # 0 - success, 1 - timeout, 2 - other error
---
float64 feedback_position   # rad
