string command                # [forward/rotate_relative/rotate_absolute]
float64 value                 # value to pass to motion function, in meters or radians
float64 velocity_linear       # [m/s]
float64 acceleration_linear   # [m/s^2]
float64 velocity_angular      # [rad/s]
float64 acceleration_angular  # [rad/s^2]
# leave velocity/acceleration value at 0 to use already configured value
---
string result                 # [success/drift]
---
