std_msgs/Header header
string odom_frame

geometry_msgs/Pose2D target

mep3_msgs/MoveProperties linear_properties
mep3_msgs/MoveProperties angular_properties
bool ignore_obstacles
bool enable_sensors
builtin_interfaces/Duration timeout
uint8 reversing
uint8 mode 7

# TODO
float64 translate_yaw_error_tolerance
---
uint8 error
---
