uint8 COMMAND_DISCONNECT = 0
uint8 COMMAND_CONNECT = 1

uint8 RESULT_DISCONNECTED = 0
uint8 RESULT_CONNECTED = 1
uint8 RESULT_CANNOT_DISCONNECT = 2
uint8 RESULT_CANNOT_CONNECT = 3

uint8 connect
---
uint8 result
---