big:
  controller_manager:
    ros__parameters:
      update_rate: 100

      diffdrive_controller:
        type: diff_drive_controller/DiffDriveController

      joint_position_controller:
        type: mep3_controllers/JointPositionController


  joint_position_controller:
    ros__parameters:
      joints:
        - m2
        - m3
        - m4
        

  diffdrive_controller:
    ros__parameters:
      left_wheel_names: ["left_motor"]
      right_wheel_names: ["right_motor"]

      odom_frame_id: odom
      base_frame_id: base_link

      wheel_separation: 0.288
      wheel_radius: 0.04075
      right_wheel_radius_multiplier: 1.0

      linear.x.has_velocity_limits: true
      linear.x.min_velocity: -2.0
      linear.x.max_velocity: 2.0
      linear.x.has_acceleration_limits: true
      linear.x.min_acceleration: -2.5
      linear.x.max_acceleration: 2.5

      angular.z.has_velocity_limits: true
      angular.z.min_velocity: -15.0
      angular.z.max_velocity: 15.0
      angular.z.has_acceleration_limits: true
      angular.z.min_acceleration: -15.0
      angular.z.max_acceleration: 15.0

      use_stamped_vel: false
