small:
  controller_manager:
    ros__parameters:
      update_rate: 100

      diffdrive_controller:
        type: diff_drive_controller/DiffDriveController
      joint_position_controller:
       type: mep3_controllers/JointPositionController
  
  joint_position_controller:
   ros__parameters:
    joints:
      - k1

  diffdrive_controller:
    ros__parameters:
      left_wheel_names: ["left_motor"]
      right_wheel_names: ["right_motor"]

      odom_frame_id: odom
      base_frame_id: base_link

      wheel_separation: 0.2685
      wheel_radius: 0.04082
      right_wheel_radius_multiplier: 1.0

      linear.x.has_velocity_limits: true
      linear.x.min_velocity: -3.0
      linear.x.max_velocity: 3.0
      linear.x.has_acceleration_limits: true
      linear.x.min_acceleration: -4.5
      linear.x.max_acceleration: 4.5

      angular.z.has_velocity_limits: true
      angular.z.min_velocity: -15.0
      angular.z.max_velocity: 15.0
      angular.z.has_acceleration_limits: true
      angular.z.min_acceleration: -25.0
      angular.z.max_acceleration: 25.0

      use_stamped_vel: false
