big:
  controller_manager:
    ros__parameters:
      update_rate: 50

  diffdrive_controller:
    ros__parameters:
      wheel_separation: 0.294
      wheel_radius: 0.0375
      right_wheel_radius_multiplier: 1.0
