name: Deploy Images to GHCR

on:
  workflow_call:
    inputs:
      flavor:
        required: false
        default: "devel"
        type: string
      base_image:
        required: false
        default: "osrf/ros:humble-desktop"
        type: string

jobs:
  push-mep3-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./docker"

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Configure Docker parameters"
        id: configure_docker_params
        run: |
          #!/bin/bash

          case ${{inputs.flavor}} in
            "vnc")
              echo "dockerfile=Dockerfile.vnc" >> $GITHUB_OUTPUT
              echo "image_name=mep3-vnc" >> $GITHUB_OUTPUT
            ;;
            *)
              echo "dockerfile=Dockerfile.base" >> $GITHUB_OUTPUT
              echo "image_name=mep3" >> $GITHUB_OUTPUT
            ;;
          esac

      - uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: docker
          file: ./docker/${{ steps.configure_docker_params.outputs.dockerfile }}
          build-args: |
            BASE_IMAGE=${{ inputs.base_image }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ steps.configure_docker_params.outputs.image_name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ steps.configure_docker_params.outputs.image_name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
